What is the difference between .drop() and .dropna()?

.drop()is used to delete the specific row and column.

.dropna() is used to drop the row and column which contain null values.

How do you change the dtype of a column — and when would you need to?

By using astype we can change the dtype of the column. we need to change the dtype when the column data does not match with the  dtype of the column. For example: age must be in integer values. but if age is in str dtype than it will e changed.

What does .apply() do and how is it different from vectorized operations?

.apply() can run a function on values like a loop. whereas the vectorized operation perform function or operation on entire array at once.

.apply() is used for complex operations or calculations also work slowly whereas the vectorized operations perform simple calculations and is fast.

Difference between .pivot() and .pivot_table()?

.pivot() is used to reshape the entire data but it doesn't handle the duplicates and null values.

.pivot_table is also to reshape the data but it can handle the missing values as well using aggregation operations like mean,median etc.

What does .merge() do and what are the 4 types of joins?

.merge() is used to combine dataframes or datasets.

inner join: It is used to join or combine the same data of both the dataframes or datasets.

left join: It will combine all the data of the left dataframes and combine the entities which are same in left dataframe and the right dataframe.

right join: complete right dataframe or dataset and matching entities in both left and right dataframe.

outer join: combine both the datasets or dataframes completely.

In [8]:
import pandas as pd

In [12]:
df = pd.read_csv("/content/SuperStoreOrders.csv.zip")
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.1400,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.0360,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.6400,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.0550,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.7700,4.70,Medium,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,CA-2014-115427,31-12-2014,4/1/2015,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14,2,0.2,4.5188,0.89,Medium,2014
51286,MO-2014-2560,31-12-2014,5/1/2015,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",4,1,0.0,0.4200,0.49,Medium,2014
51287,MX-2014-110527,31-12-2014,2/1/2015,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26,3,0.0,12.3600,0.35,Medium,2014
51288,MX-2014-114783,31-12-2014,6/1/2015,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Office Supplies,Labels,"Hon Legal Exhibit Labels, Alphabetical",7,1,0.0,0.5600,0.20,Medium,2014
51289,CA-2014-156720,31-12-2014,4/1/2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Office Supplies,Fasteners,Bagged Rubber Bands,3,3,0.2,-0.6048,0.17,Medium,2014

In [13]:
df.head(5)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [14]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

**Changing datatypes:**

In [15]:
print("Default Datatypes",df.dtypes)

Default Datatypes order_id           object
order_date         object
ship_date          object
ship_mode          object
customer_name      object
segment            object
state              object
country            object
market             object
region             object
product_id         object
category           object
sub_category       object
product_name       object
sales              object
quantity            int64
discount          float64
profit            float64
shipping_cost     float64
order_priority     object
year                int64
dtype: object

In [16]:
df["sales"] = (df["sales"].astype(str).str.replace(",", "", regex=False).astype(float))
df["order_date"] = pd.to_datetime(df["order_date"],format="mixed",dayfirst=True,errors="coerce")
df["ship_date"] = pd.to_datetime(df["ship_date"],format="mixed",dayfirst=True,errors="coerce")
print(df[["sales", "order_date", "ship_date"]].dtypes)

sales                float64
order_date    datetime64[ns]
ship_date     datetime64[ns]
dtype: object

In [17]:
print("After conversion\n",df.dtypes)

After conversion
 order_id                  object
order_date        datetime64[ns]
ship_date         datetime64[ns]
ship_mode                 object
customer_name             object
segment                   object
state                     object
country                   object
market                    object
region                    object
product_id                object
category                  object
sub_category              object
product_name              object
sales                    float64
quantity                   int64
discount                 float64
profit                   float64
shipping_cost            float64
order_priority            object
year                       int64
dtype: object

In [18]:
date_missing = df[["order_date","ship_date","sales"]].isnull().sum()
print(date_missing)

order_date    0
ship_date     0
sales         0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

**Adding new columns**

In [21]:
df["profit_margin"] = (df["profit"] / df["sales"]) * 100
#Column 2: Sales Level using apply()
df["sales_level"] = df["sales"].apply(lambda x: "High" if x >= df["sales"].median() else "Low")
df[["sales","profit","profit_margin","sales_level"]].head()

   sales   profit  profit_margin sales_level
0  408.0  106.140      26.014706        High
1  120.0   36.036      30.030000        High
2   66.0   29.640      44.909091         Low
3   45.0  -26.055     -57.900000         Low
4  114.0   37.770      33.131579        High

**Reshaping data using pivot table**

In [23]:
summary_table = df.pivot_table(index="category",values=["sales","profit"],aggfunc="sum")
summary_table

                       profit      sales
category
Furniture        286782.25380  4110884.0
Office Supplies  518473.83430  3787330.0
Technology       663778.73318  4744691.0

**Creating small dataframe and merging it**

In [24]:
category_info= pd.DataFrame({
    "category": ["Furniture","Office Supplies","Technology"],
    "category_type": ["Home Products", "Business Products", "Electronic Products"]
})
category_info

          category        category_type
0        Furniture        Home Products
1  Office Supplies    Business Products
2       Technology  Electronic Products

In [25]:
final_summary = summary.reset_index().merge(category_info,on="category",how="left")
final_summary

          category        profit      sales        category_type
0        Furniture  286782.25380  4110884.0        Home Products
1  Office Supplies  518473.83430  3787330.0    Business Products
2       Technology  663778.73318  4744691.0  Electronic Products